apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: mailhog-operator-mailhoginstance-editor-role
rules:
- apiGroups:
  - mailhog.operators.patrick.mx
  resources:
  - mailhoginstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mailhog.operators.patrick.mx
  resources:
  - mailhoginstances/status
  verbs:
  - get
