apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: mailhog-operator-mailhoginstance-viewer-role
rules:
- apiGroups:
  - mailhog.operators.patrick.mx
  resources:
  - mailhoginstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mailhog.operators.patrick.mx
  resources:
  - mailhoginstances/status
  verbs:
  - get
