---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - mailhog.operators.patrick.mx
  resources:
  - mailhoginstances
  verbs:
  - '*'
- apiGroups:
  - mailhog.operators.patrick.mx
  resources:
  - mailhoginstances/finalizers
  verbs:
  - '*'
- apiGroups:
  - mailhog.operators.patrick.mx
  resources:
  - mailhoginstances/scale
  verbs:
  - '*'
- apiGroups:
  - mailhog.operators.patrick.mx
  resources:
  - mailhoginstances/status
  verbs:
  - '*'
- apiGroups:
  - networking
  resources:
  - ingress
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
