apiVersion: v1
kind: Namespace
metadata:
  name: kuttltests
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuttl
  namespace: kuttltests
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-mailhog-kuttl-rolebinding
subjects:
  - kind: ServiceAccount
    name: kuttl
    namespace: kuttltests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mailhog-operator-manager-role
