apiVersion: v1
kind: ConfigMap
metadata:
  name: mailhog-operator-config
  namespace: mailhog-operator-system
data:
  config.yml: |-
    apiVersion: mailhog.operators.patrick.mx/v1alpha1
    kind: OperatorConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: :8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: false
      resourceName: 26f4c8adfee.mailhog.patrick.mx
    namespace: project
