apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: mailhog-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MailhogInstance is the Schema for the mailhoginstances API
      displayName: Mailhog Instance
      kind: MailhogInstance
      name: mailhoginstances.mailhog.operators.patrick.mx
      resources:
      - kind: ConfigMap
        name: ""
        version: v1
      - kind: Deployment
        name: ""
        version: v1
      - kind: DeploymentConfig
        name: ""
        version: v1
      - kind: Route
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      specDescriptors:
      - description: BackingResource controls if a deploymentConfig or deployment
          is used
        displayName: Deploy Mailhog with
        path: backingResource
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:deployment
        - urn:alm:descriptor:com.tectonic.ui:select:deploymentConfig
      - description: Image is the mailhog image to be used
        displayName: Mailhog Image
        path: image
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Replicas is the count of pods to create
        displayName: Number of pods
        path: replicas
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podCount
        - urn:alm:descriptor:io.kubernetes:custom
      - description: CorsOrigin if set, this value is added into the Access-Control-Allow-Origin
          header returned by the API
        displayName: Web CORS AllowOrigin
        path: settings.corsOrigin
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: Hostname is the hostname for smtp ehlo/helo
        displayName: SMTP Hostname
        path: settings.hostname
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: Invite set to true activates jim using the default values (see
          mh doc)
        displayName: Activate Chaosmonkey
        path: settings.jim.invite
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Storage which storage backend to use, eg memory
        displayName: Mail Storage Type
        path: settings.storage
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:memory
        - urn:alm:descriptor:com.tectonic.ui:select:maildir
        - urn:alm:descriptor:com.tectonic.ui:select:mongodb
      - description: WebTrafficInlet defines how the webinterface is exposed
        displayName: Expose Mailhog with
        path: webTrafficInlet
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:route
        - urn:alm:descriptor:com.tectonic.ui:select:none
      version: v1alpha1
  description: Deploy mailhogs on the fly
  displayName: Mailhog Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - mailhog
  - testing
  - ci
  links:
  - name: Mailhog Operator
    url: https://mailhog-operator.domain
  maintainers:
  - email: 97127469+patrickmx@users.noreply.github.com
    name: patrickmx
  maturity: alpha
  provider:
    name: patrickmx
    url: https://github.com/patrickmx
  version: 0.0.0
