apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: patrickmx-mailhog-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: ghcr.io/patrickmx/mailhog-operator-catalog:latest
  displayName: Mailhog
  publisher: patrick.mx
  updateStrategy:
    registryPoll:
      interval: 40m0s
