name: containers (tag)

on:
  push:
    tags:
      - v0.**
      - v1.**

jobs:
  ship:
    if: github.repository == 'patrickmx/mailhog-operator'
    runs-on: ubuntu-latest
    env:
      MANAGER_IMAGE_NAME: mailhog-operator
      BUNDLE_IMAGE_NAME: mailhog-operator-bundle
      CATALOG_IMAGE_NAME: mailhog-operator-catalog
      REGISTRY: ghcr.io/patrickmx
    steps:

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run unit test
        run: make test

      - name: buildah manager
        id: manager-build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.MANAGER_IMAGE_NAME }}
          tags: ${{ github.sha }} latest ${{github.ref_name}}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=Mailhog Operator (Release)
          containerfiles: |
            ./Dockerfile

      - name: GHCR login
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push manager tag image to GHCR
        id: manager-tag-push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          image: ${{ env.MANAGER_IMAGE_NAME }}
          tags: latest ${{github.ref_name}}
          registry: ${{ env.REGISTRY }}

      - name: manager tag successfully pushed
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "manager image pushed to ${{ steps.manager-tag-push-to-ghcr.outputs.registry-paths }}"

      - name: buildah bundle
        id: bundle-build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.BUNDLE_IMAGE_NAME }}
          tags: ${{ github.sha }} latest ${{github.ref_name}}
          labels: |
            org.opencontainers.image.source=https://github.com/patrickmx/mailhog-operator
            org.opencontainers.image.title=Mailhog Operator - Config Bundle (Release)
            org.opencontainers.image.description=deploy mailhogs on crc / oc
            org.opencontainers.image.revision=${{ github.sha }}
          containerfiles: |
            ./bundle.Dockerfile

      - name: push bundle tag image to GHCR
        id: bundle-tag-push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          image: ${{ env.BUNDLE_IMAGE_NAME }}
          tags: latest ${{github.ref_name}}
          registry: ${{ env.REGISTRY }}

      - name: bundle tag successfully pushed
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "bundle image pushed to ${{ steps.bundle-tag-push-to-ghcr.outputs.registry-paths }}"

      - name: Create catalog image
        run: make catalog-build-release

      - name: push catalog tag image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.CATALOG_IMAGE_NAME }}
          tags: ${{github.ref_name}}
          registry: ${{ env.REGISTRY }}

      - name: Create labeled catalog dockerfile
        run: |
          cat <<EOF >catalog.Dockerfile
          FROM ${{ env.CATALOG_IMAGE_NAME }}:${{github.ref_name}}
          LABEL \
            org.opencontainers.image.source="https://github.com/patrickmx/mailhog-operator" \
            org.opencontainers.image.title="Mailhog Operator - Catalog Index (Release)" \
            org.opencontainers.image.description="Mailhog Operator - OLM Bundle Catalog / Index Image" \
            org.opencontainers.image.revision="${{ github.sha }}"
          EOF

      - name: Add labels to catalog
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.CATALOG_IMAGE_NAME }}
          tags: latest ${{github.ref_name}}
          containerfiles: |
            ./catalog.Dockerfile

      - name: push catalog develop image to GHCR
        id: catalog-develop-push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.CATALOG_IMAGE_NAME }}
          tags: latest ${{github.ref_name}}
          registry: ${{ env.REGISTRY }}

      - name: catalog develop successfully pushed
        run: echo "catalog develop image pushed to ${{ steps.catalog-develop-push-to-ghcr.outputs.registry-paths }}"

      - name: Check image metadata
        run: |
          set -x
          mkdir -pv artifacts && cd artifacts 
          podman inspect ${{ env.MANAGER_IMAGE_NAME }}:${{github.ref_name}} >manager.json
          podman inspect ${{ env.BUNDLE_IMAGE_NAME }}:${{github.ref_name}} >bundle.json
          podman inspect ${{ env.CATALOG_IMAGE_NAME }}:${{github.ref_name}} >catalog.json
          
          cat <<EOF >NOTES.md
          # ${{ env.MANAGER_IMAGE_NAME }}:${{github.ref_name}}
          ID: $(jq '.[0].Id' manager.json)
          Diggest: $(jq '.[0].Diggest' manager.json )
          
          # ${{ env.BUNDLE_IMAGE_NAME }}:${{github.ref_name}}
          ID: $(jq '.[0].Id' bundle.json)
          Diggest: $(jq '.[0].Diggest' bundle.json )
          
          # ${{ env.CATALOG_IMAGE_NAME }}:${{github.ref_name}}
          ID: $(jq '.[0].Id' catalog.json)
          Diggest: $(jq '.[0].Diggest' catalog.json )
          EOF
          cd ..

      - uses: actions/upload-artifact@v3
        name: upload image data
        with:
          name: artifacts
          path: artifacts/
