name: containers (tag)

on:
  push:
    tags:
      - v0.**
      - v1.**

jobs:
  ship:
    if: github.repository == 'patrickmx/mailhog-operator'
    runs-on: ubuntu-latest
    env:
      MANAGER_IMAGE_NAME: mailhog-operator
      BUNDLE_IMAGE_NAME: mailhog-operator-bundle
      CATALOG_IMAGE_NAME: mailhog-operator-catalog
      REGISTRY: ghcr.io/patrickmx
    steps:

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run unit test
        run: make test

      - name: buildah manager
        id: manager-build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.MANAGER_IMAGE_NAME }}
          tags: ${{ github.sha }} latest ${{github.ref_name}}
          containerfiles: |
            ./Dockerfile

      - name: GHCR login
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push manager tag image to GHCR
        id: manager-tag-push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          image: ${{ env.MANAGER_IMAGE_NAME }}
          tags: latest ${{github.ref_name}}
          registry: ${{ env.REGISTRY }}

      - name: manager tag successfully pushed
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "manager image pushed to ${{ steps.manager-tag-push-to-ghcr.outputs.registry-paths }}"

      - name: buildah bundle
        id: bundle-build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.BUNDLE_IMAGE_NAME }}
          tags: ${{ github.sha }} latest ${{github.ref_name}}
          containerfiles: |
            ./bundle.Dockerfile

      - name: push bundle tag image to GHCR
        id: bundle-tag-push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          image: ${{ env.BUNDLE_IMAGE_NAME }}
          tags: latest ${{github.ref_name}}
          registry: ${{ env.REGISTRY }}

      - name: bundle tag successfully pushed
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "bundle image pushed to ${{ steps.bundle-tag-push-to-ghcr.outputs.registry-paths }}"

      - name: Create catalog image
        run: make catalog-build

      - name: Retag catalog as latest
        run: podman tag ghcr.io/patrickmx/mailhog-operator-catalog:${{github.ref_name}} ghcr.io/patrickmx/mailhog-operator-catalog:latest

      - name: push catalog develop image to GHCR
        id: catalog-develop-push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.CATALOG_IMAGE_NAME }}
          tags: latest ${{github.ref_name}}
          registry: ${{ env.REGISTRY }}

      - name: catalog develop successfully pushed
        run: echo "catalog develop image pushed to ${{ steps.catalog-develop-push-to-ghcr.outputs.registry-paths }}"