name: containers (tag)

on:
  push:
    tags:
      - v0.**
      - v1.**

jobs:
  test:
    name: test
    if: github.repository == 'patrickmx/mailhog-operator'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make test
      - run: make build

  ship:
    name: build images
    if: github.repository == 'patrickmx/mailhog-operator'
    runs-on: ubuntu-latest
    env:
      MANAGER_IMAGE_NAME: mailhog-operator
      BUNDLE_IMAGE_NAME: mailhog-operator-bundle
      REGISTRY: ghcr.io/patrickmx
    steps:

      - name: git clone
        uses: actions/checkout@v3

      - name: buildah manager
        id: manager-build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.MANAGER_IMAGE_NAME }}
          tags: ${{ github.sha }} latest ${{github.ref_name}} develop
          containerfiles: |
            ./Dockerfile

      - name: GHCR login
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push manager tag image to GHCR
        id: manager-tag-push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          image: ${{ env.MANAGER_IMAGE_NAME }}
          tags: latest ${{github.ref_name}} develop
          registry: ${{ env.REGISTRY }}

      - name: manager tag successfully pushed
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "manager image pushed to ${{ steps.manager-tag-push-to-ghcr.outputs.registry-paths }}"
